<?xml version="1.0" encoding="UTF-8"?>
<tileset name="jungle" tilewidth="16" tileheight="16" tilecount="741" columns="39">
 <image source="jungle.png" width="624" height="304"/>
 <tile id="39" type="Floor"/>
 <tile id="40" type="Floor"/>
 <tile id="41" type="Floor"/>
 <tile id="42" type="Floor"/>
 <tile id="43" type="Floor"/>
 <tile id="45" type="Floor"/>
 <tile id="46" type="Floor"/>
 <tile id="48" type="Floor"/>
 <tile id="50" type="Floor"/>
 <tile id="126" type="Floor"/>
 <tile id="127" type="Floor"/>
 <tile id="128" type="Floor"/>
 <tile id="129" type="Floor"/>
 <tile id="130" type="Floor"/>
 <tile id="201" type="Floor"/>
 <tile id="202" type="Floor"/>
 <tile id="273" type="Floor"/>
 <tile id="274" type="Floor"/>
 <tile id="275" type="Floor"/>
 <tile id="277" type="Floor"/>
 <tile id="278" type="Floor"/>
 <tile id="279" type="Floor"/>
 <tile id="468" type="Floor"/>
 <tile id="469" type="Floor"/>
 <tile id="470" type="Floor"/>
 <tile id="471" type="Floor"/>
 <tile id="472" type="Floor"/>
 <tile id="473" type="Floor"/>
 <tile id="474" type="Floor"/>
 <tile id="475" type="Floor"/>
 <tile id="476" type="Floor"/>
 <tile id="477" type="Floor"/>
 <tile id="507" type="Floor"/>
 <tile id="508" type="Floor"/>
 <tile id="509" type="Floor"/>
 <tile id="510" type="Floor"/>
 <tile id="511" type="Floor"/>
 <tile id="512" type="Floor"/>
 <tile id="513" type="Floor"/>
 <tile id="514" type="Floor"/>
 <tile id="515" type="Floor"/>
 <tile id="516" type="Floor"/>
</tileset>
