<?xml version="1.0" encoding="UTF-8"?>
<tileset name="jungle" tilewidth="16" tileheight="16" tilecount="741" columns="39">
 <image source="jungle.png" width="624" height="304"/>
 <tile id="39" type="Floor"/>
 <tile id="40" type="Floor"/>
 <tile id="41" type="Floor"/>
 <tile id="42" type="Floor"/>
 <tile id="43" type="Floor"/>
 <tile id="268" type="Floor"/>
 <tile id="269" type="Floor"/>
 <tile id="270" type="Floor"/>
 <tile id="271" type="Floor"/>
 <tile id="272" type="Floor"/>
 <tile id="273" type="Floor"/>
 <tile id="274" type="Floor"/>
 <tile id="275" type="Floor"/>
 <tile id="277" type="Floor"/>
 <tile id="278" type="Floor"/>
 <tile id="279" type="Floor"/>
 <tile id="280" type="Floor"/>
 <tile id="281" type="Floor"/>
 <tile id="282" type="Floor"/>
 <tile id="285" type="Floor"/>
 <tile id="286" type="Floor"/>
 <tile id="323" type="Floor"/>
 <tile id="324" type="Floor"/>
 <tile id="325" type="Floor"/>
 <tile id="326" type="Floor"/>
 <tile id="386" type="Floor"/>
 <tile id="387" type="Floor"/>
 <tile id="388" type="Floor"/>
 <tile id="468" type="Floor"/>
 <tile id="469" type="Floor"/>
 <tile id="470" type="Floor"/>
 <tile id="471" type="Floor"/>
 <tile id="472" type="Floor"/>
 <tile id="473" type="Floor"/>
 <tile id="474" type="Floor"/>
 <tile id="475" type="Floor"/>
 <tile id="476" type="Floor"/>
 <tile id="477" type="Floor"/>
 <tile id="636" type="Floor"/>
 <tile id="637" type="Floor"/>
 <tile id="638" type="Floor"/>
 <tile id="639" type="Floor"/>
</tileset>
