<?xml version="1.0" encoding="UTF-8"?>
<tileset name="jungle" tilewidth="16" tileheight="16" tilecount="741" columns="39">
 <image source="jungle.png" width="624" height="304"/>
 <tile id="39" type="Floor"/>
 <tile id="40" type="Floor"/>
 <tile id="41" type="Floor"/>
 <tile id="42" type="Floor"/>
 <tile id="43" type="Floor"/>
 <tile id="45" type="Floor"/>
 <tile id="46" type="Floor"/>
 <tile id="66" type="Floor"/>
 <tile id="67" type="Floor"/>
 <tile id="68" type="Floor"/>
 <tile id="69" type="Floor"/>
 <tile id="70" type="Floor"/>
 <tile id="72" type="Floor"/>
 <tile id="73" type="Floor"/>
 <tile id="74" type="Floor"/>
 <tile id="93" type="Floor"/>
 <tile id="94" type="Floor"/>
 <tile id="95" type="Floor"/>
 <tile id="99" type="Floor"/>
 <tile id="100" type="Floor"/>
 <tile id="101" type="Floor"/>
 <tile id="126" type="Floor"/>
 <tile id="127" type="Floor"/>
 <tile id="128" type="Floor"/>
 <tile id="129" type="Floor"/>
 <tile id="130" type="Floor"/>
 <tile id="144" type="Floor"/>
 <tile id="145" type="Floor"/>
 <tile id="146" type="Floor"/>
 <tile id="147" type="Floor"/>
 <tile id="148" type="Floor"/>
 <tile id="150" type="Floor"/>
 <tile id="151" type="Floor"/>
 <tile id="152" type="Floor"/>
 <tile id="268" type="Floor"/>
 <tile id="269" type="Floor"/>
 <tile id="270" type="Floor"/>
 <tile id="271" type="Floor"/>
 <tile id="272" type="Floor"/>
 <tile id="273" type="Floor"/>
 <tile id="274" type="Floor"/>
 <tile id="275" type="Floor"/>
 <tile id="277" type="Floor"/>
 <tile id="278" type="Floor"/>
 <tile id="279" type="Floor"/>
 <tile id="280" type="Floor"/>
 <tile id="281" type="Floor"/>
 <tile id="282" type="Floor"/>
 <tile id="285" type="Floor"/>
 <tile id="286" type="Floor"/>
 <tile id="323" type="Floor"/>
 <tile id="324" type="Floor"/>
 <tile id="325" type="Floor"/>
 <tile id="326" type="Floor"/>
 <tile id="328" type="Floor"/>
 <tile id="329" type="Floor"/>
 <tile id="330" type="Floor"/>
 <tile id="331" type="Floor"/>
 <tile id="332" type="Floor"/>
 <tile id="333" type="Floor"/>
 <tile id="334" type="Floor"/>
 <tile id="336" type="Floor"/>
 <tile id="337" type="Floor"/>
 <tile id="338" type="Floor"/>
 <tile id="386" type="Floor"/>
 <tile id="387" type="Floor"/>
 <tile id="388" type="Floor"/>
 <tile id="406" type="Floor"/>
 <tile id="407" type="Floor"/>
 <tile id="408" type="Floor"/>
 <tile id="410" type="Floor"/>
 <tile id="411" type="Floor"/>
 <tile id="412" type="Floor"/>
 <tile id="414" type="Floor"/>
 <tile id="415" type="Floor"/>
 <tile id="416" type="Floor"/>
 <tile id="468" type="Floor"/>
 <tile id="469" type="Floor"/>
 <tile id="470" type="Floor"/>
 <tile id="471" type="Floor"/>
 <tile id="472" type="Floor"/>
 <tile id="473" type="Floor"/>
 <tile id="474" type="Floor"/>
 <tile id="475" type="Floor"/>
 <tile id="476" type="Floor"/>
 <tile id="477" type="Floor"/>
 <tile id="636" type="Floor"/>
 <tile id="637" type="Floor"/>
 <tile id="638" type="Floor"/>
 <tile id="639" type="Floor"/>
</tileset>
